on:
  push:
    branches:
      - main
      - develop
      # testing
      - feat/testing-setup
  pull_request:
    branches:
      - main
      - develop
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: run containers
        run: docker compose -f docker-compose-tests.yaml up -d --build

      - name: list containers
        run: docker ps -a

      - name: report status
        run: docker logs fastapi-cognito-fastapi_cognito_tests-1

      - name: stop containers
        if: always()
        run: docker compose -f docker-compose-tests.yaml down
  